version: '3'

services:
  web:
    build:
      context: .
      dockerfile: compose/web/Dockerfile
    container_name: shiritori
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn shiritori.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./src:/src
      - ./src/static:/src/static
    expose: 
      - "8000"
    # networks:
    #   - nginx_network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./src/static:/src/static
    depends_on: # basically says, "wait for web(shiritori) app to be ready before starting this service"
      - web
    # networks:
    #   - nginx_network

# networks:
#   nginx_network:
#     driver: bridge