version: '3'

services:
  app:
    build:
      context: .
      dockerfile: compose/app/Dockerfile
    container_name: shiritori
    volumes:
      - ./src:/src
  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src